SELECT
    EMP.LAST_NAME,
    EMP.HIRE_DATE,
    MNG.LAST_NAME,
    MNG.HIRE_DATE
FROM
    EMPLOYEES EMP
    LEFT JOIN
    EMPLOYEES MNG
    ON EMP.MANAGER_ID = MNG.EMPLOYEE_ID
WHERE
    EMP.HIRE_DATE < MNG.HIRE_DATE;