SELECT
    LAST_NAME,
    JOB_ID,
    DEPARTMENT_ID,
    DEPARTMENTS.DEPARTMENT_NAME
FROM
    EMPLOYEES
        NATURAL JOIN
    DEPARTMENTS
        NATURAL JOIN
    LOCATIONS
WHERE
    LOCATIONS.CITY = 'Toronto';