SELECT 
CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(EMPLOYEE_ID, ','), FIRST_NAME), ','), CONCAT(CONCAT(CONCAT(FIRST_NAME, ','), LAST_NAME), ',')),
CONCAT(CONCAT(CONCAT(CONCAT(EMAIL, ','), PHONE_NUMBER), ','), CONCAT(CONCAT(CONCAT(HIRE_DATE, ','), JOB_ID), ','))),
CONCAT(CONCAT(CONCAT(CONCAT(SALARY, ','), COMMISSION_PCT), ','), CONCAT(CONCAT(MANAGER_ID, ','), DEPARTMENT_ID))) AS THE_OUTPUT
FROM EMPLOYEES;