ACCEPT MANAGER NUMBER PROMPT 'Manager';
ACCEPT column_name CHAR PROMPT 'Column name'
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE MANAGER_ID = &MANAGER
ORDER BY &column_name;