SELECT
    EMP.LAST_NAME,
    EMP.EMPLOYEE_ID,
    MNG.LAST_NAME,
    MNG.EMPLOYEE_ID
FROM
    EMPLOYEES EMP
    LEFT JOIN
    EMPLOYEES MNG
    ON EMP.MANAGER_ID = MNG.EMPLOYEE_ID
WHERE
    MNG.LAST_NAME IS NOT NULL OR EMP.LAST_NAME = 'King'
ORDER BY
    EMP.EMPLOYEE_ID;